name: jaguar_query_sqflite_example
description: Example for Jaguar Query sqflite adapter
version: 3.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

flutter:

dependencies:
  flutter:
    sdk: flutter
  jaguar_query_sqflite_nullsafety:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
