name: jaguar_query_nullsafety
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.3.0
homepage: https://github.com/xxzj990/jaguar_orm_nullsafe
# documentation:

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.17.10
