name: jaguar_query_nullsafety
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 3.0.0
homepage: https://github.com/maxleexyz/jaguar_orm_nullsafe

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: any

dev_dependencies:
  test: ^1.17.10
